// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tseauddartilhawqycqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZWF1ZGRhcnRpbGhhd3F5Y3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTY0OTIsImV4cCI6MjA2NDM5MjQ5Mn0.O405jpptBpqLV4_jD-KSx5kkBJQnhwn6WGtp87Sb714";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);